### ISSUE TITLE
Integrate Weather API

### ISSUE THREAD

**Issue by asouer** [CapstoneProj4/MWMFlask#4]

**Comment by pi6220na** [comment]
Closing issue. The weather API calls have been integrated into Project 4. Modal windows are used to display:
- Current Conditions
- Forecast Conditions
- An animated (gif) weather Radar image of the Twin Cities Area
Logging, error handling, caching on two API calls (third 'call', is done dynamically when gif image is displayed), and commenting incorporated into the Project.
